# See COPYRIGHT file at the top of the source tree.
"""A framework for measuring and defining performance metrics that can be
submitted to the SQUASH service.
"""

try:
    # version.py is auto-generated by sconsUtils
    from .version import *  # noqa: F403
except:
    __version__ = "unknown"

from .base import *  # noqa: F403
