# See COPYRIGHT file at the top of the source tree.
"""Framework for measuring and defining performance metrics that can be
submitted to the SQUASH service.
"""

try:
    # version.py is auto-generated by sconsUtils
    from .version import *  # noqa: F403
except:
    __version__ = "unknown"

from .errors import *  # noqa: F403
from .datum import *  # noqa: F403
from .spec import *  # noqa: F403
from .metric import *  # noqa: F403
from .measurement import *  # noqa: F403
from .blob import *  # noqa: F403
from .job import *  # noqa: F403
from .output import *
