#
# LSST Data Management System
#
# This product includes software developed by the
# LSST Project (http://www.lsst.org/).
#
# See COPYRIGHT file at the top of the source tree.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the LSST License Statement and
# the GNU General Public License along with this program.  If not,
# see <https://www.lsstcorp.org/LegalNotices/>.
#
"""LSST Science Pipelines Verification Framework."""

try:
    # version.py is auto-generated by sconsUtils
    from .version import *
except:
    __version__ = "unknown"

from .errors import *
from .datum import *
from .naming import *
from .metaquery import *
from .spec import *
from .specset import *
from .metric import *
from .metricset import *
from .measurement import *
from .measurementset import *
from .blob import *
from .blobset import *
from .jobmetadata import *
from .job import *
from .output import *
from .metricTask import *
